# Generated by Django 5.2.6 on 2026-04-05 13:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_weeklyplan'),
        ('exercises', '0003_alter_exercise_external_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')])),
                ('label', models.CharField(blank=True, default='', max_length=12)),
                ('day_type', models.CharField(choices=[('workout', 'Workout'), ('rest', 'Rest'), ('recovery', 'Recovery')], default='rest', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_min', models.PositiveIntegerField(default=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'day_of_week', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlanExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('sets', models.PositiveIntegerField(blank=True, null=True)),
                ('reps', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_min', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='weeklyplan',
            options={'ordering': ['-week_start_date', '-created_at']},
        ),
        migrations.RenameField(
            model_name='weeklyplan',
            old_name='generated_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='weeklyplan',
            name='plan_json',
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='profile_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='title',
            field=models.CharField(default='AI Weekly Plan', max_length=120),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='today_tip',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='week_start_date',
            field=models.DateField(default=datetime.date(2026, 3, 30)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['user', 'week_start_date'], name='assistant_w_user_id_530986_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['user', 'is_active'], name='assistant_w_user_id_3acb0b_idx'),
        ),
        migrations.AddConstraint(
            model_name='weeklyplan',
            constraint=models.UniqueConstraint(fields=('user', 'week_start_date', 'is_active'), name='unique_active_weekly_plan_per_user_week'),
        ),
        migrations.AddField(
            model_name='weeklyplanday',
            name='weekly_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='assistant.weeklyplan'),
        ),
        migrations.AddField(
            model_name='weeklyplanexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_plan_links', to='exercises.exercise'),
        ),
        migrations.AddField(
            model_name='weeklyplanexercise',
            name='weekly_plan_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_exercises', to='assistant.weeklyplanday'),
        ),
        migrations.AddConstraint(
            model_name='weeklyplanday',
            constraint=models.UniqueConstraint(fields=('weekly_plan', 'day_of_week'), name='unique_day_per_weekly_plan'),
        ),
    ]
