# Generated by Django 5.2.6 on 2026-03-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_frequency_customuser_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='endurance_level',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='workout_duration',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='workout_place',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
