# Generated by Django 5.2.6 on 2026-04-05 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercise_categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Exercise Category',
                'verbose_name_plural': 'Exercise Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='exercises.exercisecategory')),
            ],
            options={
                'verbose_name': 'Exercise Subcategory',
                'verbose_name_plural': 'Exercise Subcategories',
                'ordering': ['category__sort_order', 'sort_order', 'name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('target_muscle', models.CharField(blank=True, default='', max_length=120)),
                ('equipment', models.CharField(blank=True, default='', max_length=120)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('instructions', models.TextField(blank=True, default='')),
                ('tips', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/')),
                ('video_url', models.URLField(blank=True, default='')),
                ('default_sets', models.PositiveIntegerField(blank=True, null=True)),
                ('default_reps', models.PositiveIntegerField(blank=True, null=True)),
                ('default_duration_min', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.exercisecategory')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='exercises.exercisesubcategory')),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'ordering': ['category__sort_order', 'subcategory__sort_order', 'sort_order', 'name'],
            },
        ),
    ]
