# Generated by Django 5.2.6 on 2026-04-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='asset_image_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='exercise',
            name='asset_video_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='exercise',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
