# Generated by Django 5.2.6 on 2026-04-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_asset_image_name_exercise_asset_video_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='external_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
