# Generated by Django 5.2.6 on 2026-04-06 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistant', '0002_weeklyplanday_weeklyplanexercise_and_more'),
        ('exercises', '0003_alter_exercise_external_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgressSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_workouts', models.PositiveIntegerField(default=0)),
                ('total_reps', models.PositiveIntegerField(default=0)),
                ('average_form_score', models.FloatField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('best_exercise', models.CharField(blank=True, default='', max_length=150)),
                ('last_workout_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress_snapshot', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('total_duration_sec', models.PositiveIntegerField(default=0)),
                ('total_reps', models.PositiveIntegerField(default=0)),
                ('avg_form_score', models.FloatField(blank=True, null=True)),
                ('calories_burned', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled'), ('in_progress', 'In Progress')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
                ('weekly_plan_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_sessions', to='assistant.weeklyplanday')),
            ],
            options={
                'ordering': ['-finished_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(blank=True, default='', max_length=150)),
                ('exercise_slug', models.CharField(blank=True, default='', max_length=180)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('completed_sets', models.PositiveIntegerField(blank=True, null=True)),
                ('completed_reps', models.PositiveIntegerField(default=0)),
                ('duration_sec', models.PositiveIntegerField(default=0)),
                ('avg_form_score', models.FloatField(blank=True, null=True)),
                ('detected_mistake', models.CharField(blank=True, default='', max_length=150)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_exercises', to='exercises.exercise')),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workoutsession')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', '-finished_at'], name='workouts_wo_user_id_cddba7_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', 'status'], name='workouts_wo_user_id_8a43bb_idx'),
        ),
    ]
